### ISSUE TITLE
Inject key differently

### ISSUE THREAD

**Issue by spekulatius** [jwelmac/php-sdk-fcm#2]
Hello @jwelmac 

Thanks for publishing your library. I had a look at your library and like the simple clean structure. The only thing I noticed I would consider doing differently is the way the api key is added. I would prefer to hand it to the library instead of editing a file - this way the library can be checked into VCS/updated without concerns. What do you think?

If you like to I can provide you with a pull request for my suggestion.

Cheers,
Peter

**Comment by jwelmac** [comment]
Hey @spekulatius,
I think that is a great idea.
Please go ahead and send the pull request.

**Comment by jwelmac** [comment]
Thanks for your enhancement to this library.
Your pull request has been incorporated with some modifications to ensure that previous installations are not broken by the update.
